### ISSUE TITLE
Questions Session #1

### ISSUE THREAD

**Issue by dmitriys-lits** [pani-tka/gitter-frontend-client#11]
@pani-tka collect please your questions here as a comments

![image](https://user-images.githubusercontent.com/20638114/47912171-5e1ea380-dea0-11e8-8eff-aee59406ed85.png)

**Comment by pani-tka** [comment]
Есть у нас метод,
 `selectRoom = (roomID) => {
    this.setState({
      selectedRoomID: roomID,
    });
  }`
который влияет на состояние приложения через свойство selectedRoomID,в которое будет принимать значение  id выбранной комнаты (RoomID) и тогда  в событии handleClick происходит переприсваивание с RoomID на id. 
но  RoomID кроме как тут больше нигде не фигурирует и нет начального состояния ,чтоб туда можно было что-то занести или как это работает? 

handleClick.

`handleClick = event => {
    event.preventDefault() 
    const {id, isSelected, selectRoom} = this.props;

    if ( !isSelected) {
      selectRoom(id);
    }
  };
`
 - Это событие по клику вызывает метод  selectRoom и в случае,если комната выбрана заносит туда 
       как аргумент id выбранной комнаты вместо roomID ? 
 - Почему изменилась форма записи  e на event ?
 - Почему handleClick вызывается в ссылке,а не в блоке <div className={containerClassName}> ?
 И еще по поводу него 

 const containerClassName = isSelected
    ? `${styles.container} ${styles.selected}`
    : styles.container; 
ClassName - нужно переименовать или в этом особый смысл?
Смысл этого в том,чтоб если комната выбрана, то применить применить к ней стили  {styles.selected} ,если нет, то styles.container, но почему такая форма записи?
я понимаю,что в обычных ковычках,можно вывести только текст,в то время как в обратном апострофе можно вставить переменную или выражение, но в  эту конструкцию ${ } ,если я правильно все поняла, но в целом  `${styles.container} ${styles.selected}` не могу уловить суть
но просто судет складывать слили? Это {styles.container} плюс это {styles.selected} ?

еще видела такое $ ( ) , в чем разница?

**Comment by dmitriys-lits** [comment]
All questions are answered.
