### ISSUE TITLE
Work with npm and yarn

### ISSUE THREAD

**Issue by pani-tka** [pani-tka/gitter-frontend-client#23]

**Comment by pani-tka** [comment]
Not started cause  I didn’t have any guidance on this topic.

**Comment by dmitriys-lits** [comment]
The questions:

1. What is npm? Which components compose NPM (hint: CLI tool, registry, website)? Tell a short definition.
2. What is npm package? What is `package.json`? What is local package and what is global package? What is `$PATH`?
3. What is `dependencies` and `devDependencies` sections? What is `scripts` section?
3. What is `node_modules` folder? Could you delete it? How to install all packages? How to install concrete package? How to upgrade packages? Which arguments do you know for those commands? How to run the commans from scripts section?
4. What is semver? Describe meaning of `patch`, `minor change` and `major change`.
5. What is `package-lock.json`?  Which reasons to have `package-lock.json`? Should you keep it under git? Could you delete it?
6. How to reinstall node modules?

And

7. What is yarn? When `yarn` released and why? Which benefits of `yarn`? What a difference with `npm`?
8. Study the same things about yarn (install/delete/upgrade commands and their arguments).
9. Delete in your project `package-lock.json` and `yarn.lock` if exists. Try install packages via `npm` and after instal packages via `yarn`.
10. Is this okay to use both package managers `yarn` and `npm`? Is this okay to have both lock files `package-lock.json` and `yarn.lock`?
11. Imagine that you become a lead developer on the new project from scratch. You have a choice about default package manager for project. Which package manager you choose and why?
