### ISSUE TITLE
Regular Expressions

### ISSUE THREAD

**Issue by dmitriys-lits** [pani-tka/gitter-frontend-client#25]
**Open:**

https://regexr.com/43igc

**Read the tutorial:**

https://medium.com/factory-mind/regex-tutorial-a-simple-cheatsheet-by-examples-649dc1c3f285

Try different example from tutorial on https://regexr.com/43igc and see how it works

*Tip: you could use any another article, it's just first example from Google*

**Be ready to answer the questions:**

1. What is regular expressions?
2. Give examples of simplest regular expression.
3. What are doing `[]` brackets in regular expressions?
4. What are doing `()` brackets in regular expressions?
5. What are doing `{}` brackets in regular expressions?
6. What is doing `|` symbol in regular expressions?
7. What is quantification? How to specify matches quantity? List all methods.
8. How names `\w`, `\W` characters? What them mean? List all and describe meaning.
9. What means `/g` and `/i` in regular expressions?

**Write next regular expressions:**

1. Regular expression which match all words with length lesser 6
2. Regular expression which match all occurences "Katya" or "Kateryna"
3. Regular expression which match all words in lower case
4. Regular expression which match all words with capitalized first latter
5. Regular expression which match all emails
6. Regular expression which match all urls
7. Regular expression which match all words with first symbol `$` but without number after `$`. Examples of occurences: `$vasua`, `$capitan`, `$pizza33`. Examples of mismatching: `$1music`

**How to use regular expressions in javascript?**

That's it.

**Comment by pani-tka** [comment]
Just started.

**Comment by pani-tka** [comment]
[https://codepen.io/pani-tka/pen/jdyELZ](url)

**Comment by dmitriys-lits** [comment]
Good work! 👍
