### ISSUE TITLE
Chat scrolling issue

### ISSUE THREAD

**Issue by dmitriys-lits** [pani-tka/gitter-frontend-client#30]
![screll-bug](https://user-images.githubusercontent.com/20638114/48973711-e41cad00-f04e-11e8-8e59-e658ce216fc5.gif)

The current behavior is not correct as you could see on the screencast. A user would like to see latest messages without scrolling. You should make a scroll manually programmatically instead of user.

Steps to do it:

1. Study refs in React JS https://reactjs.org/docs/refs-and-the-dom.html

The questions for you: what are the references in the React JS? Why we need it? Give examples when we need the references.

2. Try to use reference. Add the button with text "Scroll To End" on `RoomView` component. And implement next - when user clicks the button - chat should be scrolled to end.

3. Remove the button and use the same logic at moment when messages loaded.

Don't hesitate ask me questions if you have :-)

**Comment by pani-tka** [comment]
Done.
