### ISSUE TITLE
Theory and practice

### ISSUE THREAD

**Issue by dmitriys-lits** [pani-tka/gitter-frontend-client#31]
Прочитать полностью:

http://learn.javascript.ru/data-structures

Все разделы по порядку. Всего 11 разделов. В некоторых разделах в конце приводятся задачи, решить самостятельно пару из них для каждого. Если что-то не получается - можно подсмотреть решение, но тогда решить следующую самостоятельно. Читать вдумчиво, если непонятно - перечитывать или пробовать в консоли браузера.

По итогу я в режимо созвона пробегусь по всем разделам и задам вопросы по каждому из них.

Для того, чтобы упростить задачу, некоторые вопросу озвучу тут, отвечать на них нужно будет устно:

**Числа:**

1. Какие методы округления числа существуют в JS?
2. Чему будет результат выполнения `0.1 + 0.2 === 0.3`?
3. Чем отличается `==` от `===`?
4. Как из числа получить строку с значением числа?
5. Как из строки с числом получить число?

**Строки:**

1. Какие специальные символы ты знаешь?
2. Как узнать длину строки?
3. Как получить третий символ строки?

**Объекты:**

1. Разница между проверками in и === undefined?
2. Решить задачу в конце статьи.

**Перебор объектов:**

1. Как перебрать все свойства объекта?
2. Решить три задачи в конце статьи.

**Объекты: передача по ссылке**

1. Что значит передача по ссылке? Чем отличается от копирования?

**Массивы с числовыми индексами**

1. Чем массив отличается от объекта?
2. Какие методы есть у массива?
3. Решить три задачи в конце.

**Comment by dmitriys-lits** [comment]
https://codepen.io/dmitriys-lits/pen/yQZgJj?editors=1111

**Comment by pani-tka** [comment]
Done, but I would repeat it later.

**Comment by dmitriys-lits** [comment]
good, it's enough for me that you know about all these things, but you could repeat them if feel necessary
