### ISSUE TITLE
DOM partial

### ISSUE THREAD

**Issue by dmitriys-lits** [pani-tka/gitter-frontend-client#32]
Вдумчиво прочитать и изучить:

1. http://learn.javascript.ru/searching-elements-dom

Все исключая секцию про `XPath`. Уметь объяснить как работает каждый метод для поиска DOM элементов (своими словами)

2. http://learn.javascript.ru/metrics

Уметь объяснить из чего состоят размеры элементов, какие есть свойства и что означают, и какие свойства можно менять.

Решить пару задач в конце

3. For your information  (FYI)- http://learn.javascript.ru/dom-console

4. FYI - http://learn.javascript.ru/basic-dom-node-properties

Чем отличается innerHTML от outerHTML и от textContent?
Решить одну задачу.

5. FYI - http://learn.javascript.ru/dom-polyfill

Что такое полифиллы? 

6. FYI - http://learn.javascript.ru/metrics-window

**Comment by pani-tka** [comment]
Done.
